# Generated by Django 4.0.3 on 2022-07-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=25)),
                ('lastName', models.CharField(blank=True, max_length=25)),
                ('userType', models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('conCreator', 'CONTENT CREATOR'), ('others', 'Others')], max_length=100, null=True)),
                ('organization', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(blank=True, max_length=11)),
                ('emailAddress', models.EmailField(blank=True, max_length=254)),
                ('homeAddress', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeG', models.CharField(max_length=100)),
                ('gadgetname', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('mesCon', models.TextField(blank=True)),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TMTsys.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateField(blank=True)),
                ('delProcess', models.CharField(max_length=100)),
                ('modPay', models.CharField(max_length=100)),
                ('cash', models.CharField(blank=True, max_length=12)),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TMTsys.user')),
            ],
        ),
    ]
