# Generated by Django 4.0.3 on 2022-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMTsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='dateOrder',
            field=models.CharField(max_length=100),
        ),
    ]
