# Generated by Django 4.0.3 on 2022-07-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMTsys', '0002_alter_delivery_dateorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='uid',
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TMTsys.delivery')),
                ('gadget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TMTsys.gadget')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TMTsys.user')),
            ],
        ),
    ]
